package me.kingofdanether.survivalgames.enumeration;

public enum GameState {
	
	LOBBY_WAITING, LOBBY_COUNTDOWN, INGAME_WAITING, INGAME_COUNTDOWN, INGAME_STARTED, INGAME_DEATHMATCH, INGAME_DEATHMATCH_WAITING, INGAME_DEATHMATCH_COUNTOWN, POSTGAME_ENDING, POSTGAME_REBUILDING;
	
}
